server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: ${SSL_KEYSTORE_PASSWORD:changeit}
    key-store-type: PKCS12
    key-alias: cryptowallet
  error:
    include-stacktrace: never
    include-message: never

spring:
  application:
    name: crypto-wallet-backend

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:cryptowallet}
    username: ${DB_USERNAME:wallet_user}
    password: ${DB_PASSWORD:secure_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        use_sql_comments: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        generate_statistics: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 2000ms
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms

  security:
    require-ssl: true

# Application-specific configuration
crypto:
  wallet:
    security:
      jwt:
        secret-key: ${JWT_SECRET:your-ultra-secure-jwt-secret-key-minimum-512-bits}
        expiration-time: 900000 # 15 minutes
        refresh-expiration-time: 604800000 # 7 days

      encryption:
        master-key: ${MASTER_ENCRYPTION_KEY:your-master-key-for-aes-256}
        key-derivation:
          iterations: 1000000
          salt-length: 64

      rate-limiting:
        login-attempts: 5
        login-window-minutes: 15
        api-requests-per-minute: 100

      password:
        min-length: 12
        require-uppercase: true
        require-lowercase: true
        require-numbers: true
        require-special: true
        max-age-days: 90

      session:
        timeout-minutes: 30
        max-concurrent: 3

      audit:
        enabled: true
        log-all-requests: true
        sensitive-data-masking: true

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized

# Logging configuration
logging:
  level:
    com.cryptowallet: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/crypto-wallet.log
  logback:
    rollingpolicy:
      max-size: 10MB
      max-history: 30

# Custom properties for different environments
---
spring:
  config:
    activate:
      on-profile: prod

server:
  port: 8443

crypto:
  wallet:
    security:
      encryption:
        use-hsm: true
        hsm-slot: 0
      rate-limiting:
        api-requests-per-minute: 50
      session:
        timeout-minutes: 15

logging:
  level:
    root: WARN
    com.cryptowallet: INFO